# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0fde9b3d-a2f9-49da-a4a7-440b7026a26e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-0fde9b3d-a2f9-49da-a4a7-440b7026a26e".device = "/dev/disk/by-uuid/0fde9b3d-a2f9-49da-a4a7-440b7026a26e";
  boot.initrd.luks.devices."luks-41e06b79-012c-418d-8d72-e0de00555fe3".device = "/dev/disk/by-uuid/41e06b79-012c-418d-8d72-e0de00555fe3";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-0fde9b3d-a2f9-49da-a4a7-440b7026a26e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-0fde9b3d-a2f9-49da-a4a7-440b7026a26e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DFF6-769E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-41e06b79-012c-418d-8d72-e0de00555fe3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
